### ISSUE TITLE
Source of Football Info

### ISSUE THREAD

**Issue by VasilyShelkov** [Winwardo/solid-octo-disco#1]
Finding a public rest API for football related information such as:
-> Teams
-> Players
-> Match Data

**Comment by VasilyShelkov** [comment]
http://www.jokecamp.com/blog/guide-to-football-and-soccer-data-and-apis/

**Comment by VasilyShelkov** [comment]
http://www.programmableweb.com/category/all/apis?keyword=football is a website to search many available APIs

**Comment by VasilyShelkov** [comment]
@Winwardo If you're happy with http://api.football-data.org/index(check out the docs) then add it to the readme so we don't forget it as a source and close this issue :) 

I found this looking pretty extensively at all the available options in the above 2 sources

**Comment by Winwardo** [comment]
I've signed up and got an API key, seems pretty awesome!

And you've looked at all the other options? I'm happy to just use this but if there were any other decent ones we could also collect data from do say

**Comment by VasilyShelkov** [comment]
Basing on what we need think  http://api.football-data.org/index is sufficient
