### ISSUE TITLE
Merely hitting enter is not enough for searching

### ISSUE THREAD

**Issue by Winwardo** [Winwardo/solid-octo-disco#105]
Right now it's very hard to search for specific paramtype, as one need to enter the query (which is then searched automatically), then change the paramtypes, and then enter another query to tell the search to run again.

Similarly, removing a query does not run the search again.

I propose we either
a) add a "Search" button, or 
b) run a search on any event in the search bar; e.g. adding a term, removing a term, changing paramTypes

@VasilyShelkov thoughts?

**Comment by VasilyShelkov** [comment]
I think this is a fix to do with changing paramTypes as opposed to adding a 'search' button... same with removing a term personally.

I'd prefer not having a search button, because it just feels that much more fluid, intuitive and reactive.

What do you think ?

**Comment by Winwardo** [comment]
Then I think we should go with b - always run a new search on any of the main events.

**Comment by VasilyShelkov** [comment]
kl, yer that's what I'd prefer to do I'll change this to an improvement then :)
