### ISSUE TITLE
QuotedTweet Timeout so not forever loading

### ISSUE THREAD

**Issue by VasilyShelkov** [Winwardo/solid-octo-disco#138]
shouldn't use in src/client/results/Feed.js:231

```
getInitialState() {
   return {
     tweetContent: null,
   };
}
```

instead see https://facebook.github.io/react/docs/reusable-components.html#es6-classes in particular the constructor part of it.

Also after some time, we should just show an error screen that the fetch from twitter failed.

**Comment by Winwardo** [comment]
So the only time we'll see this is if we have a quote within a quote.
This can be more easily solved by simply adding a "isQuote" prop to <Tweet /> and not allowing it to attempt to show its own quote if it is already one itself.

**Comment by VasilyShelkov** [comment]
This has been fixed by using constructor in Quoted Tweet
