### ISSUE TITLE
Storage of Twitter Data

### ISSUE THREAD

**Issue by VasilyShelkov** [Winwardo/solid-octo-disco#3]
The retrieved queries need to be stored as:
-a source of data 
-cache to reduce the number of queries to Twitter

GraphQL/Relational/NoSQL?

**Comment by Winwardo** [comment]
OrientDB would be nice but if it's easier to pick MySQL go with that - we know for sure we have the CiCS database available.
Don't know about Mongo?

**Comment by Winwardo** [comment]
If we do use OrientDB, we can do super cool graph searches, and even suggest related players - "People who tweet at this footballer, also tweet at this one!"
