### ISSUE TITLE
Make the showing/hiding labels in the feed only appear if they're > 0

### ISSUE THREAD

**Issue by VasilyShelkov** [Winwardo/solid-octo-disco#79]
Also make it a vbit prettier :)

**Comment by Winwardo** [comment]
@VasilyShelkov I don't understand this issue, could you elaborate or add a screenshot please?

**Comment by VasilyShelkov** [comment]
feed.js line 10 onwards

```
<h3>Search results, showing {filteredFeed.length} posts.</h3>
      (Hiding {feed.length - filteredFeed.length} posts)
```

atm it doesn't look nice and there's little reason to say showing: 0, hiding {posts.length} or showing {posts.length}, hiding 0 since it's giving unnecessary extra detail.. the showing or hiding should only display if > 0 

and format it more nicely X)

**Comment by Winwardo** [comment]
Ah, I completely understand now. :+1:
