### ISSUE TITLE
Most Active Users

### ISSUE THREAD

**Issue by VasilyShelkov** [Winwardo/solid-octo-disco#81]
- Component for the most active users based on the users with the most tweets in the results feed.
- Have a search action to be able to find particular users like in most used words
- Be able to filter the results by checkbox of user tweets like filtering most used words

**Comment by Winwardo** [comment]
Solid issue :+1:

**Comment by VasilyShelkov** [comment]
Better ? X) cba initially

**Comment by VasilyShelkov** [comment]
duplicate issue #77
