### ISSUE TITLE
Geolocation selection from tweet can fail

### ISSUE THREAD

**Issue by Winwardo** [Winwardo/solid-octo-disco#85]
This is currently mitigated in #84 by wrapping in a try/catch, but it's indicative of the code below not correctly checking before trying to access [0]

**Comment by VasilyShelkov** [comment]
@Winwardo can you give me a search query where it didn't work for you ? 

My suspicions are its this part:

```
if (rawTweet.place) {
    return {
      latitude: rawTweet.place.bounding_box.coordinates[0][0][1],
      longitude: rawTweet.place.bounding_box.coordinates[0][0][0],
    };
```

Since it may not have a bounding_box or the coordinates may not be a 3d array...

but I want to try it obviously, and can't seem to get a query which bugs it out :S

**Comment by Winwardo** [comment]
I had to try a bunch of different queries before it happened, it's not easy to reproduce sadly :/ Can try to get a solid repro once I'm back in the flat
